

# To create the blank file with permission.

- hosts: web1
  tasks:
    - file:
         path: /opt/data/perm.txt
         state: touch
         mode: '0640'

# To create the new file and add the content. 

- hosts: web1
  tasks:
  - lineinfile:
      path: /var/www/html/index.html
      line: 'This line was added using Ansible lineinfile module!'
      create: yes

# To check the file with condition on size and age. 

- hosts: web1
  tasks:
    - name: Find files
      find:
        paths: /opt/data
        recurse: yes
        size: 1m
        age: 120
        age_stamp: atime
      register: file

    - debug:
        var: file

    - name: Copy files
      command: cp {{ item.path }} /opt
      with_items: "{{ file.files }}"


# To insert the line to file. 

 - name: Add block to index.html
   hosts: web1
   tasks:
    - blockinfile:
       owner: apache
       group: apache
       insertbefore: BOF
       path: /var/www/html/index.html
       block: |
        Welcome to KodeKloud!
        This is Ansible Lab.

# Replace module to find and replace the content. 

- hosts: web1
  tasks:
  - replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: 'Listen 80'
      replace: 'Listen 8080'
  - service:
      name: httpd
      state: restarted

