
# Download roles.
# ansible-galaxy install role-name 


# Using Roles

- name: Deploy MySQL Server
  hosts: db_server
  roles:
  - kodekloud1.mysql


# To install role in current directory. 

ansible-galaxy install geerlingguy.nginx -p ./roles/
- downloading role 'nginx', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/3.1.0.tar.gz
- extracting geerlingguy.nginx to /home/thor/playbooks/web/roles/geerlingguy.nginx
- geerlingguy.nginx (3.1.0) was installed successfully


# To pass variable value to the roles. It can override the value in roles. 

- name: Deploy Web Server
  hosts: web_server
  roles:
  - name: geerlingguy.nginx
    vars:
      nginx_service_enabled: no


# To create new role in given directory.

ansible-galaxy init roles/ansible-role-firewalld

