
# Ansible is idempodent. Started means if already started then no change. If not started, then only wil start.
-
    name: 'Execute a script on all web server nodes'
    hosts: web_nodes
    tasks:
        -
            name: 'Execute a script on all web server nodes'
            script: /tmp/install_script.sh
            register: result 
        -
            name: 'Start service httpd, if not started'
            service:
              name: httpd
              state: started
