
   - name: Install MariaDB package
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: installed

    - name: Create Mysql configuration file
      template: src=templates/my.cnf.j2 dest=/etc/my.cnf

    - name: Start MariaDB Service
      service: name=mariadb state=started enabled=yes
    - name: Start firewalld
      service: name=firewalld state=started enabled=yes
      