
---
- name: Deploy lamp stack application
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: tasks/common.yml
# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  gather_facts: yes
  become: yes
  tasks:
  - include_tasks: tasks/db.yml
- hosts: lampweb
  become: yes
  gather_facts: yes
  tasks:
  - include_tasks: tasks/web.yml
  